language: php

jobs:
   include:
      -  os: windows
         language: shell
         before_install:
            - choco config set cacheLocation $HOME/choco_cache
            - choco install php --version 7.4 --no-progress
            - choco install composer --no-progress
            - wget -O ffmpeg.7z https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z
            - 7z e ffmpeg.7z *.exe -r
            - mv *.exe /c/tools/
            - cp $TRAVIS_BUILD_DIR/tests/windows_files/* $SYSTEMROOT/system32
            - export PATH="/c/tools/php74:/c/tools:/c/ProgramData/ComposerSetup/bin/:$PATH"
         install:
            - composer install --no-interaction
         cache:
            directories:
               - $LOCALAPPDATA/Composer/files
               - $TRAVIS_BUILD_DIR/tests/test_data
               - $HOME/choco_cache
      -  os: linux
         php: '7.1'
      -  php: '7.2'
      -  php: '7.3'
      -  php: '7.4'
      -  php: '8.0'
      -  php: 'nightly'
      -  php: '7.4'
         name: 'Prefer lowest'
         install:
            - composer install --no-interaction
            - composer update --prefer-lowest

   allow_failures:
      -  php: 'nightly'

addons:
   apt:
      packages:
         - ffmpeg
         - mediainfo

env:
   global:
      - XDEBUG_MODE=coverage

cache:
   directories:
      - $HOME/.cache/composer/files
      - $TRAVIS_BUILD_DIR/tests/test_data

before_install:
   - bash -c 'echo $TRAVIS_OS_NAME'

install:
   - composer install --no-interaction;

before_script:
   - vendor/bin/phpunit --version

script:
   - vendor/bin/phpunit

after_script:
  - bash <(curl -s https://codecov.io/bash)