language: php

jobs:
   include:
      -  os: windows
         language: shell
         before_install:
            - choco install php --version 7.4
            - choco install composer
            - choco install ffmpeg
            - export PATH="/c/tools/php74:/c/ProgramData/ComposerSetup/bin/:/c/ProgramData/chocolatey/lib/ffmpeg/tools:$PATH"
         install:
            - composer install --no-interaction --ignore-platform-reqs;
      -  os: linux
         php: '7.1'
      -  php: '7.2'
      -  php: '7.3'
      -  php: 'nightly'
         install:
            - composer install --no-interaction --ignore-platform-reqs;
      -  php: '7.4'
         after_script:
            - bash <(curl -s https://codecov.io/bash)
      -  php: '7.4'
         name: 'Prefer lowest'
         install:
            - composer install --no-interaction
            - composer update --prefer-lowest

   allow_failures:
      -  php: 'nightly'
      -  os: windows

addons:
   apt:
      packages:
         - ffmpeg
         - mediainfo
cache:
   directories:
      - $HOME/.cache/composer/files
      - $TRAVIS_BUILD_DIR/tests/test_data

before_install:
   - bash -c 'echo $TRAVIS_OS_NAME'

install:
   - composer install --no-interaction;

before_script:
   - vendor/bin/phpunit --version

script:
   - vendor/bin/phpunit
