language: php

matrix:
   include:
      -  os: windows
         language: sh
         before_install:
            - choco install php --version 7.4
            - choco install composer
            - choco install ffmpeg
            - export PATH="/c/tools/php74:/c/ProgramData/ComposerSetup/bin/:/c/ProgramData/chocolatey/lib/ffmpeg/tools:$PATH"
         install:
            - composer install --no-interaction --ignore-platform-reqs;
      -  os: linux
         php: '7.3'
      -  php: 'nightly'
         install:
            - composer install --no-interaction --ignore-platform-reqs;
      -  php: '7.4'
      -  php: '7.4'
         name: 'Prefer lowest'
         install:
            - composer install --no-interaction
            - composer update --prefer-lowest

   allow_failures:
      -  php: 'nightly'
      -  os: windows

addons:
   apt:
      packages:
         - ffmpeg
         - mediainfo

before_install:
   - bash -c 'echo $TRAVIS_OS_NAME'

install:
   - composer install --no-interaction;

before_script:
   - vendor/bin/phpunit --version
   #- mkdir tests/test_data
   - wget -O tests/test_data/sample.mp4 http://techslides.com/demos/samples/sample.mp4

script:
   - vendor/bin/phpunit

after_script:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash <(curl -s https://codecov.io/bash); fi