language: php

jobs:
   include:
      -  os: windows
         language: shell
         install:
            - choco install vcredist-all
            - export PATH="/c/tools/php74:/c/tools:/c/ProgramData/ComposerSetup/bin/:/c/ProgramData/chocolatey/lib/ffmpeg/tools:$PATH"
            - wget -O /c/tools/ffprobe.exe http://dedicated.datagutten.net/ffprobe.exe
            - cp $TRAVIS_BUILD_DIR/tests/windows_files/* $SYSTEMROOT/system32
         script:
            - ffprobe -show_entries format=duration -i $TRAVIS_BUILD_DIR/tests/test_data/sample.mp4
