language: php

jobs:
   include:
      -  os: windows
         language: shell
         before_install:
            - choco install php --version 7.4
            - choco install composer
            - export PATH="/c/tools/php74:/c/tools:/c/ProgramData/ComposerSetup/bin/:/c/ProgramData/chocolatey/lib/ffmpeg/tools:$PATH"
            - wget -O /c/tools/ffprobe.exe http://dedicated.datagutten.net/ffprobe.exe
            - cp $TRAVIS_BUILD_DIR/tests/windows_files/* $SYSTEMROOT/system32
         install:
            - composer install --no-interaction --ignore-platform-reqs;
         cache:
            directories:
               - $LOCALAPPDATA/Composer/files
               - $TRAVIS_BUILD_DIR/tests/test_data
         after_script:
            - ffprobe -show_entries format=duration -i $TRAVIS_BUILD_DIR/tests/test_data/sample.mkv

addons:
   apt:
      packages:
         - ffmpeg
         - mediainfo
cache:
   directories:
      - $HOME/.cache/composer/files
      - $TRAVIS_BUILD_DIR/tests/test_data

before_install:
   - bash -c 'echo $TRAVIS_OS_NAME'

install:
   - composer install --no-interaction;

before_script:
   - vendor/bin/phpunit --version

script:
   - vendor/bin/phpunit
