#!/usr/bin/php
<?php

use datagutten\video_tools\video_download;

require $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

if (!file_exists($argv[1]))
    die("File not found\n");

$file = video_download::mkvmerge($argv[1]);
printf("Merged %s to %s\n", $argv[1], $file);