#!/usr/bin/php
<?php

use datagutten\tools\files\files;

require __DIR__.'/loader.php';

if(!file_exists($argv[1]))
    die("File not found\n");

$file = \datagutten\video_tools\video_download::mkvmerge($argv[1]);
printf("Merged %s to %s\n", $argv[1], $file);