#!/usr/bin/php
<?Php
//find -name \*.no.vtt -exec php /home/video-tools/scripts/vtt_to_srt {} \;
use datagutten\video_tools\subtitles\vtt_to_srt;

require __DIR__.'/loader.php';
$convert = new vtt_to_srt();
$convert->convert_file($argv[1]);