name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', 'latest' ]
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            ffmpeg_install: sudo apt-get install ffmpeg mediainfo
          - os: windows-latest
            ffmpeg_install: choco install --no-progress ffmpeg

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Set chocolatey cache path
        if: ${{ runner.os == 'Windows' }}
        run: choco config set cacheLocation $HOME/choco_cache

      - name: Cache Chocolatey packages
        id: choco-cache
        uses: actions/cache@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          path: ~/choco_cache
          key: chocolatey

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: libxml, gd, pdo

      - name: Install ffmpeg
        run: ${{ matrix.ffmpeg_install }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: composer run-script test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  prefer_lowest:
    name: 'Prefer lowest dependency versions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          extensions: libxml, gd, pdo

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Install dependencies
        run: composer update --prefer-lowest --no-progress

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1