name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', 'latest' ]
        os: [ ubuntu-latest, windows-latest ]
        experimental: [ false ]
        include:
          - os: ubuntu-latest
            ffmpeg_install: sudo apt-get install ffmpeg mediainfo
          - os: windows-latest
            ffmpeg_install: choco install --no-progress ffmpeg
          - php: 8.1
            os: ubuntu-latest
            experimental: true
          - php: 8.1
            os: windows-latest
            experimental: true

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-

      - name: Install ffmpeg
        run: ${{ matrix.ffmpeg_install }}

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: libxml, gd, pdo

      - name: Install dependencies
        if:  ${{ matrix.experimental == false }}
        run: composer install --prefer-dist --no-progress

      - name: Install dependencies
        if:  ${{ matrix.experimental == true }}
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Run tests
        run: composer run-script test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  prefer_lowest:
    name: 'Prefer lowest dependency versions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          extensions: libxml, gd, pdo

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Install dependencies
        run: composer update --prefer-lowest --no-progress

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1